# Generated by Django 2.2.3 on 2019-07-29 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='probelms',
            new_name='problem',
        ),
    ]
