# Generated by Django 2.2.3 on 2019-08-05 19:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20190730_0125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentConetst',
            new_name='StudentContest',
        ),
    ]
